# ignoring photon_spectator from github so that we can use local version with bugfix
# ref: https://github.com/golang/dep/issues/935#issuecomment-448291002
# ignored = ["github.com/broderickhyman/photon_spectator"]

[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  name = "github.com/google/gopacket"
  revision = "1a2aa715ae412f434ae0bbb833442d14880cab8a"

[[constraint]]
  name = "github.com/broderickhyman/photon_spectator"
  source = "https://github.com/gradiuscypher/photon_spectator.git"
  branch = "gopacket-fix"

[[constraint]]
  name = "github.com/mitchellh/go-ps"

[[constraint]]
  name = "github.com/mitchellh/mapstructure"

[[constraint]]
  name = "github.com/broderickhyman/go-githubupdate"
  branch = "master"

[[constraint]]
  name = "github.com/shirou/gopsutil"
  source = "https://github.com/gradiuscypher/gopsutil.git"
  revision = "d573c8e3f1c5337585b0e285214e80df7429d8b5"

[[constraint]]
  name = "golang.org/x/tools"

[[constraint]]
  name = "github.com/nats-io/go-nats"
  version = "1.3.0"

[[constraint]]
  name = "github.com/getlantern/systray"

[[constraint]]
  name = "github.com/mattn/go-colorable"
