version: 2
jobs:
  test:
    working_directory: /go/src/github.com/regner/albionmarket-client
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      - run: go get golang.org/x/tools/cmd/goimports
      - run: make validate-fmt
  build_windows:
    working_directory: /go/src/github.com/regner/albionmarket-client
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      - run: sudo apt-get install -y build-essential mingw-w64
      - run: curl https://glide.sh/get | sh
      - run: glide install
      - run: make build-windows
      - persist_to_workspace:
          root: /go/src/github.com/regner/albionmarket-client
          paths:
            - albionmarket-client.exe
  deploy:
    working_directory: /tmp/workspace
    docker:
      - image: circleci/golang:1.8
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: go get github.com/tcnksm/ghr
      - run: ghr -u regner -r albionmarket-client `git describe --tags` .
workflows:
  version: 2
  test_build_release:
    jobs:
      - test
      - build_windows:
          requires:
            - test
      - deploy:
          requires:
            - build_windows
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

