version: 2
jobs:
  test:
    working_directory: /go/src/github.com/regner/albionmarket-client
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      - run: go get golang.org/x/tools/cmd/goimports
      - run: make validate-fmt
  build_windows:
    working_directory: /go/src/github.com/regner/albionmarket-client
    docker:
      - image: regner/golang
    steps:
      - checkout
      - run: apt-get update && apt-get install -y build-essential mingw-w64
      - run: go get -u github.com/golang/dep/cmd/dep
      - run: dep ensure
      - run: make build-windows
      - run: gzip -9 albionmarket-client.exe
      - run: mv albionmarket-client.exe.gz update-windows-amd64.exe.gz
      - store_artifacts:
          path: /go/src/github.com/regner/albionmarket-client/update-windows-amd64.exe.gz
      - persist_to_workspace:
          root: /go/src/github.com/regner/albionmarket-client
          paths:
            - update-windows-amd64.exe.gz
  build_linux:
    working_directory: /go/src/github.com/regner/albionmarket-client
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      - run: sudo apt-get install -y libpcap-dev
      - run: go get -u github.com/golang/dep/cmd/dep
      - run: dep ensure
      - run: go build -ldflags "-s -w -X main.version=`git describe --tags`" cmd/albionmarket-client/albionmarket-client.go      
      - run: gzip -9 albionmarket-client
      - run: mv albionmarket-client.gz update-linux-amd64.gz
      - store_artifacts:
          path: /go/src/github.com/regner/albionmarket-client/update-linux-amd64.gz
      - persist_to_workspace:
          root: /go/src/github.com/regner/albionmarket-client
          paths:
            - update-linux-amd64.gz
  build_darwin:
    working_directory: /go/src/github.com/regner/albionmarket-client
    docker:
      - image: pcdummy/crossbuild-golang:1.8.3
    steps:
      - checkout
      - run: apt-get update && apt-get install -y libpcap-dev
      - run: go get -u github.com/golang/dep/cmd/dep
      - run: dep ensure
      - run: env OSXCROSS_NO_INCLUDE_PATH_WARNINGS=1 MACOSX_DEPLOYMENT_TARGET=10.6 CC=/usr/osxcross/bin/o64-clang CXX=/usr/osxcross/bin/o64-clang++ GOOS=darwin GOARCH=amd64 CGO_ENABLED=1 go build -ldflags "-s -w -X main.version=`git describe --tags`" cmd/albionmarket-client/albionmarket-client.go      
      - run: gzip -9 albionmarket-client
      - run: mv albionmarket-client.gz update-darwin-amd64.gz
      - store_artifacts:
          path: /go/src/github.com/regner/albionmarket-client/update-darwin-amd64.gz
      - persist_to_workspace:
          root: /go/src/github.com/regner/albionmarket-client
          paths:
            - update-darwin-amd64.gz            
  deploy:
    working_directory: /tmp/workspace
    docker:
      - image: circleci/golang:1.8
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: go get github.com/tcnksm/ghr
      - run: ghr -u regner -r albionmarket-client `git describe --tags` .
workflows:
  version: 2
  test_build_release:
    jobs:
      - test
      - build_windows:
          requires:
            - test
      - build_linux:
          requires:
            - test
      - build_darwin:
          requires:
            - test
      - deploy:
          requires:
            - build_windows
            - build_linux
            - build_darwin
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/

